apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: n8n
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/n8nio/n8n:latest
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "true"
            - name: N8N_BASIC_AUTH_USER
              value: "false"   # set real value in Cloud Run console
            - name: N8N_BASIC_AUTH_PASSWORD
              value: "false"   # set real value in Cloud Run console
            - name: DB_TYPE
              value: "postgresdb"
            - name: DB_POSTGRESDB_CONNECTION_URL
              value: "false"   # set your Neon connection string in Cloud Run console
            - name: N8N_ENCRYPTION_KEY
              value: "false"   # set your encryption key in Cloud Run console
          ports:
            - containerPort: 5678
      timeoutSeconds: 300
