services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_PORT
        value: 10000
      - key: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
        value: true
    dockerCommand: n8n start --tunnel
