services:
  - type: web
    name: n8n
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: false        # set real value in Render Dashboard
      - key: N8N_BASIC_AUTH_PASSWORD
        value: false        # set real value in Render Dashboard
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_CONNECTION_URL
        value: false        # set in Render Dashboard
      - key: N8N_ENCRYPTION_KEY
        value: false        # set in Render Dashboard
      - key: N8N_PORT
        value: 10000
    dockerCommand: n8n start
